### ISSUE TITLE
S2: Forum Creation and Setup (8, Must Have)

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/Level-Lounge#10]
As a user, I wish to participate in discussions about games so that I can connect with the community.

### Acceptance Criteria
- Users should be able to create forum threads and posts in different categories (e.g., Game Discussion, Reviews).
- Forum posts should be stored in the database and associated with the correct user.
- Users should be able to reply to threads and participate in ongoing discussions.

### Tasks
- [x] Design and implement forum threads and categories.
- [x] Create forms for thread creation and replies.
- [x] Store and display forum posts in the database.
