### ISSUE TITLE
S2: Basic Game Rating System (5, Won't Have)

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/Level-Lounge#11]
As a user, I wish to rate games within forum threads so that I can share my opinion with the community.

### Acceptance Criteria
- Users should be able to give a numeric rating (e.g., 1-5 stars) within specific threads.
- Ratings should be associated with the user's post in the thread.
- Ratings should be stored in the database for potential aggregation.

### Tasks
- [ ] Implement a rating input within forum posts.
- [ ] Store ratings alongside posts in the database.
- [ ] Display ratings next to user posts in the relevant threads.
