### ISSUE TITLE
S3: User Profile Setup (5, Must Have)

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/Level-Lounge#14]
As a user, I wish to view and customize my profile so that I can manage my account information and contributions.

### Acceptance Criteria
- Users should be able to view their profile with details like username, reputation, and post history.
- Users should be able to edit basic profile information (e.g., bio, profile picture).

### Tasks
- [x] Implement profile view with post history.
- [x] Create forms for editing profile information.
- [x] Allow user to update and delete information on their profile.
