### ISSUE TITLE
S4: Bug Fixes and Refinements (8, Must Have)

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/Level-Lounge#17]
As a developer, I wish to refine the existing features based on testing and feedback so that the user experience is smooth.

### Acceptance Criteria
- All critical bugs identified during testing should be fixed.
- UI/UX issues identified during testing should be addressed.
- The site should function smoothly without major usability issues.

### Tasks
- [x] Prioritize and fix bugs identified during testing.
- [x] Refine the user interface based on feedback or testing insights.
- [x] Ensure all features are working as intended with no major usability issues.
