### ISSUE TITLE
S3: User can like posts (5, Should Have)

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/Level-Lounge#20]
As a user I want to be able to like posts that I agree with or I feel invoke good conversation.

## Acceptance Criteria
- User is able to like posts.
- User can remove likes from posts and can only like a post once.
- Like count is displayed on forum post.

## Tasks
- [ ]  Add a likes field to the Post model to track the number of likes.
- [ ] Create a relationship between the User and Post models to track which users have liked which posts.
- [ ] Implement the "like" button in the post template, updating the count dynamically.
- [ ] Ensure that users can only like a post once and can remove their like.
