### ISSUE TITLE
S1: Create Posts (5, Must, Have)

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/Level-Lounge#22]
As a user, I want to create and publish posts so that I can share my thoughts and ideas with others.

## Acceptance Criteria
- Users should be able to create a new post with a title and content.
- Published posts should be visible to all users and displayed in the list of posts.
- The published post should have a unique URL based on its slug.

## Tasks
- [x]  Implement the post creation form with fields for title and content.
- [x]  Add a slug field to the 'Post' model to generate a unique URL.
- [x] Create a view to handle the post creation and publishing process.
- [x] Update the post list view to display published posts.
- [x] Write tests to ensure posts can be created and are visible to other users.
