### ISSUE TITLE
User Story 0.6: User Login (3, Must Have)

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/Level-Lounge#24]
As a user, I can log in to my account so that I can access personalized features and manage my posts.

## Acceptance Criteria
- User can log in through a button in the navigation. 
- User must be told when they are logged in.
- Log in must be secure with error handling.

## Tasks
- [x] Log in link in navigation
- [x] 'You are logged in as...' must be displayed on the screen
- [x] Use Django AllAuth to secure login.
