### ISSUE TITLE
User Story S2: Edit Profile and Bio (13, Must Have)

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/Level-Lounge#27]
As a user, I can view and edit my profile so that I can keep my personal information, profile picture and bio up to date.

## Acceptance Criteria
- Users can view their profile.
- They can add a bio to their profile.
- They can add a profile picture of themselves if they wish.
- Users have a default profile image if they do not choose to add one themselves.

## Tasks
- [x] Profile view linked in the navigation.
- [x] Edit profile form with field for bio.
- [x] Use cloudinary to add images to their profile
- [x] Set default image for users that don't choose to have a profile image.
