### ISSUE TITLE
S1: Home Page Setup (3, Must Have)

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/Level-Lounge#7]
As a user, I wish to see a welcoming home page that provides navigation to different site sections.

### Acceptance Criteria
- The home page should display a navigation bar with links to the main sections: Forum, Profile, etc.
- The home page should have a welcoming message or site introduction.
- The home page should be accessible to all users, whether logged in or not.

### Tasks
- [x] Design and implement the home page layout.
- [x] Create navigation links to key site sections.
- [x] Add a site introduction or welcome message.
